Update pins to reflect usage, add new functionality, and specify i2c communication.
lukejenkins/minibadge pull request #5
Opened 2021-05-31 22:16 UTC by Sodium-Hydrogen

Update pins to reflect usage:
* Remove SPI as it was never supported by a badge
* Make them programming pins that future badges leave not connected.
* Change 5v to vbatt

New functionality
* Added low frequency clock pin to sync updates and drive simple ICs like a decade counter.

2021-06-01 18:13 UTC, karrots commented
VBatt should probably specify a max voltage of 5 volts to prevent burning things up if the battery source were ever changed to something not LiPo in the future.

2021-06-02 21:40 UTC, lukejenkins requested changes
Don't strip my credit, this isn't saintcon's project it is mine. Collaborate don't clobber.

Also do not strip out the Sparkfun credit.

2021-06-03 16:37 UTC, lukejenkins commented
You know what, between all of the work on documenting the i2c and that dropping SPI _MIGHT_ cause some issues if anyone happened to implement it. I think a 2.0 tag is in order. @Sodium-Hydrogen If you agree, please change your pull request to use 2.0 rather than 1.1.

2021-06-03 17:00 UTC, Sodium-Hydrogen commented
Sounds good. Also @karrots I put extra emphasis in the readme that `+VBATT` should max out at +5v

2021-09-04 15:35 UTC, merged

2021-09-04 15:36 UTC, lukejenkins commented
Nice work!